### ISSUE TITLE
Module does not work on Mendix 7.3

### ISSUE THREAD

**Issue by rcha103** [mendix/MxPushNotifications#55]
I have encountered an issue on Mendix 7.3. I'm using the Push Notifications Demo project to test it on Mendix 7.3. A few of the issues:

- Online Hybrid Mobile App profile causes the widget to throw an error (looking from the console error it only says 'error: not implemented'. Not sure why is this)

- Switching back to Offline Hybrid Mobile App resolves the error above. However, the device never gets registered even after hitting the Sync button and the Refresh Devices button.

I can confirm the module and Demo project worked on Mendix 6.10.3. I can't afford to downgrade to Mendix 6 due to client requirements.

**Comment by Mocke44** [comment]
I encounter the same issue using mx 7.3. Desperately looking for a fix. Please advize

**Comment by KevinVlaanderen** [comment]
We've implemented a fix for this issue. The new mpk is currently available in PR #57. We'll merge the fix and release it to the AppStore once the fix has been confirmed.
Please let us know whether this indeed fixes the issue for you.

**Comment by rcha103** [comment]
Hi @KevinVlaanderen thanks, I can confirm that the new mpk file fixes the issue. However, I have encountered yet another issue regarding APN setup. The Java action StartAPN does not work properly (again on Mx 7.3.0) when executed from microflow RestartAPN, making it impossible to start the APN and send push notifications to iOS devices. Please advise, thanks!

**Comment by KevinVlaanderen** [comment]
Thank you for the feedback. We'll look into it right away.

**Comment by Mocke44** [comment]
Hi have tested and confirmed Android devices are registering and receiving
push notifcations, not tested on IOS though.

Thanks for the quick fix!

**Comment by KevinVlaanderen** [comment]
With Mx7, jars that are bundled with the runtime are not automatically available to custom Java actions anymore. This happens e.g. with the slf4j library, which seems to cause the runtime error that @rcha103 reported.

This means that, for Mx7 apps that use the PushNotifications Connector module, you'll need to add the slf4j jar-file to your <project-dir>/userlib folder. I have attached the appropriate file. Please extract the zip file into your userlib folder and verify that this solves the issue.

We'll look into fixing the PushNotifications Connect module in the AppStore, so that this is properly fixed.

[org.slf4j.slf4j-api.jar.zip](https://github.com/mendix/MxPushNotifications/files/1091123/org.slf4j.slf4j-api.jar.zip)

**Comment by rcha103** [comment]
Thanks for the fix @KevinVlaanderen . The APN configuration now works fine and it restarts as expected. However, the iOS devices never receives the notification even if the message gets sent to the APN service, at least that's what I found out from my testing result. Notifications works fine on Android though. Any advice? I followed step by step from [https://docs.mendix.com/howto6/setting-up-apple-push-notification-server](url) and set the DTAP mode as production.

**Comment by BlokJan** [comment]
Hi,

I'm working with Mendix 7.4.0.
Downloading the mpk from git indeed solved previous issue.
But now I get "PushNotification.init is not a function".

Config.xml generated by mendix says:
<plugin name="phonegap-plugin-push" source="npm" spec="1.5.3" />

Could you please solve this issue ?

**Comment by BlokJan** [comment]
Hi Kevin,

Any clues on this ?

Thanks,
Jan

**Comment by KevinVlaanderen** [comment]
With release 3.0.0, this issue should be resolved.

**Comment by mmehmetAliIzci** [comment]
Im closing this issue due to inactivity. 

You can always re-open if issue still persists.
